const URLS = {
    all: 'all',
    add: 'add',
    edit: 'edit',
    info: 'info',
    signin: 'signin',
    forgotPassword: 'forgot-password',
    acceptInvite: 'accept-invite',
    home: 'dashboard',
    configuration: 'configuration',
    userManagement: 'user-management',
    tax: 'tax',
    generalInformation: 'general-information',
    products: 'products',
    variants: 'variants',
    categories: 'categories',
    newMainCategory: 'new-main',
    newSubCategory: 'new-sub',
    editMainCategory: 'edit-main',
    editSubCategory: 'edit-sub',
    newSuperSubCategory: 'new-super-sub',
    editSuperSubCategory: 'edit-super-sub',
    collections: 'collections',
    productGroups: 'product-groups',
    brands: 'brands',
    discounts: 'discounts',
    reporting: 'reporting',
    shipping: 'shipping',
    customers: 'customers',
    orders: 'orders',
    draftOrders: 'draft-orders',
    orderLogs: 'order-logs',
    addChildOrder: 'add-child',
    editMainOrder: 'edit-main',
    editChildOrder: 'edit-child',
    pages: 'pages',
    homepage: 'homepage',
    vendors: 'vendors',
    navigations: 'navigations',
    headerCustomization: 'header-customization',
    footerCustomization: 'footer-customization',
    zones: 'zones',
    shippingRates: 'shipping-rates',
    defaultShipping: 'default-shipping',
    filters: 'filters',
    loyality: 'loyality',
    coupons: 'coupons',
    shippingRegions: 'shipping-regions',
    country: 'country',
    cities:'cities',
    smsConfiguration: 'sms-configuration',
    smsProvider: 'sms-provider',
    smsTemplate: 'sms-template',
    smsLogs: 'sms-logs',
    emailConfiguration: 'email-configuration',
    emailProvider: 'email-provider',
    emailTemplate: 'email-template',
    emailLogs: 'email-logs',
    checkoutCustomization: 'checkout-customization',
    contentApproval: 'content-approval',
    pushNotification: 'push-notification',
    sendNotification: 'send-notification',
    featuredApps: 'featured-apps',
    sizeChart: 'size-chart',
    createSizeChart: 'create-size-chart',
    wishList: 'wish-list',
    wishListProduct: 'wish-list-product',
    wishListCustomer: 'wish-list-customer',
    cacheSetting: 'cache-setting',
    preferences: 'preferences-settings',
    productSocialFeed: 'product-social-feed',
    createProductSoclialFeed: 'create-product-social-feed',
    paymentGateways: 'payment-gateway',
    paymentGatewayForm: 'payment-gateway-form',
    storeLocator: 'store-locator',
    createStoreLocator: 'create-store-locator',
    timeSlot: 'time-slot',
    createTimeSlot: 'create-time-slot',
    editTimeSlot: 'edit-time-slot',
    orderReturn: 'order-return',
    jobPosting: 'job-posting',
    createJobPosting: 'create-job-posting',
    editJobPosting: 'edit-job-posting',
    jobDetail: 'job-detail',
    applicantDetail: 'applicant-detail',
    salesRporting: 'sales-reporting',
    salesRportSetting: 'sales-report-setting',
    multiLocation: 'multi-location',
    locations:'locations',
    createLocation:'create-location',
    editLocation:'edit-location',
    locationDetail:'location-detail',
    logisticConfiguration: 'logistics-configuration',
    courierIntegration: 'couriers-integrations',
    addCourierConfiguration: 'add-courier-integrations',
    courierAutomation: 'courier-automation',
    courierPriority: 'courier-priority',
    internationalCourierPriority: 'international-courier-priority',
    courierInvoiceSetting: 'courier-invoice-setting',
    erp: 'erp',
    storeSetting: 'store-setting',
    productsReviews: 'all-customer-reviews',
    productReviewDetail: 'product-review-detail'

    


}

export default URLS;